### ISSUE TITLE
Conexão básica client-servidor

### ISSUE THREAD

**Issue by Wilgnne** [Wilgnne/uWebSocket#1]
Realizar uma conexão simples entre um cliente Unity com um servidor NodeJS

**Comment by wilgnne** [comment]
Com o fim do desenvolvimento da aplicação de chat creio que chegamos ao fim de uma etapa.
Até o momento a biblioteca já é capaz de gerenciar eventos e conexões, e até realizar broadcast para os cliente conectados.
Creio que isto finalize o ciclo de conexão básica! 🎉
### Que possamos agora ultrapassar desafios ainda maiores!
